import Head from "next/head";
import styles from "@/styles/Home.module.css";
import Navbar from "@/components/navbar/Navbar";
import Button from "@/components/button/Button";
import axios from "axios";
import Router from "next/router";
import Maping from "@/components/mapping/Maping";
import SortButton from "@/components/sortbutton/SortButton";
import { useState, useEffect } from "react";

export default function Home(props) {
  const [questions, setQuestions] = useState(props.questions);
  const [allQuestions, setAllQuestions] = useState(props.questions);
  const [filter, setFilter] = useState("");
  const [buttonValue, setButtonValue] = useState(false);

  const onChangeFilterInputHander = (eventValue) => {
    setFilter(eventValue);
  };

  const zeroAnswers = (data) => {
    return data.filter((data) => data.answerId.length === 0);
  };

  useEffect(() => {
    buttonValue
      ? setQuestions(zeroAnswers(allQuestions))
      : setQuestions(allQuestions);
  }, [buttonValue]);

  const sortButton = () => {
    buttonValue ? setButtonValue(false) : setButtonValue(true);
  };

  const isLoged = () => {
    axios
      .get("http://localhost:3002/checkLoginStatus", {
        headers: { user_jwt: localStorage.getItem("user_jwt") },
      })
      .then((res) => {
        // console.log(res.data.status);
        Router.push("/askQuestion/");
      })
      .catch((err) => {
        // console.log(err.response.data.status);
        alert(err.response.data.status);
      });
  };

  return (
    <>
      <Head>
        <title>10 MONTHS</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Navbar text={"Gal kas atsakys ..."} />
        <div className={styles.buttonWraper}>
          <Button text={"Ask Question"} onClick={isLoged} />
        </div>

        <div className={styles.sortFindWraper}>
          <input
            placeholder="Find Question By Title"
            value={filter}
            onChange={(text) => onChangeFilterInputHander(text.target.value)}
          />
          <div>
            <SortButton
              text={buttonValue ? "All" : "Not Answered"}
              onClick={sortButton}
            />
          </div>
        </div>

        <div className={styles.infoBox}>
          {questions
            .filter((question) => question.title.includes(filter))
            .map((question) => {
              return <Maping trip={question} />;
            })}
        </div>
      </main>
    </>
  );
}

export async function getServerSideProps(contex) {
  // console.log("contex", contex);

  const response = await axios.get("http://localhost:3002/questionsWithUsers");
  console.log(response.data.questions);
  return {
    props: {
      questions: response.data.questions,
    },
  };
}
